### PR TITLE
Gossip functions update

### LINKED ISSUE #1: [Error] Compile errors
After recent major updates, module is not ready for compile.

### PR DESCRIPTION
**Pull request by Nefertumm**
Closes #1

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
tested?

i feel like it's good to merge

**Comment by BarbzYHOOL** [comment]
I don't have the issue mentioned so I didn't use this PR and everything works fine, so I'm perplexed

**Comment by BarbzYHOOL** [comment]
I think the old method still work but the new one is of course preferred, i'll try to test this PR when i think about it !

**Comment by Helias** [comment]
What about a little test and merge? @Nefertumm @BarbzYHOOL

**Comment by Nefertumm** [comment]
It works well

**Pull request merged**
